### ISSUE TITLE
can't remove pomodoros from outcomes on timeline page

### ISSUE THREAD

**Issue by aspiers** [aspiers/complice#13]
When submitting / editing outcomes on the timeline page, it's possible to add an unlimited number of pomodoros to any outcome, but if you add too many, you can't remove them.

**Comment by ssaadh** [comment]
Yeah I've run into this twice recently. Not a big deal though!

**Comment by malcolmocean** [comment]
You actually can, via-shift-clicking, but it's not at all intuitive. I'll add a hover title saying 'shift-click to remove' right now.
