### ISSUE TITLE
Make Chrome New Tab Page available for Firefox

### ISSUE THREAD

**Issue by micgro42** [aspiers/complice#16]
The new tab page for Chrome is great! But I use Firefox as my main browser, so it would be awesome if the new tab page would be available there as well.

As [adviced by the docs](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Porting_a_Google_Chrome_extension), I uploaded the extension's crx file to the official [Chrome->Firefox extension tester](https://www.extensiontest.com/) and the APIs are compatible!

So porting this extension seems to be only a matter of updating some dependencies and maybe some minor adjustments. I'd love to help with some pull request, but couldn't find the repository.

Would you consider porting this very useful extension to Firefox?

**Comment by micgro42** [comment]
I received access to the repository and I'm looking into creating the necessary adjustments.

**Comment by malcolmocean** [comment]
This is completed now!

https://addons.mozilla.org/en-US/firefox/addon/complice-new-tab-page/
